//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charac_Generator_DH2 {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Mondes_natals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Mondes_natals() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Charac_Generator_DH2.Resources Mondes natals", typeof(Resources_Mondes_natals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;&lt;Workbook xmlns:c=&quot;urn:schemas-microsoft-com:office:component:spreadsheet&quot; xmlns:html=&quot;http://www.w3.org/TR/REC-html40&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot; xmlns:x2=&quot;http://schemas.microsoft.com/office/excel/2003/xml&quot; xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot; xmlns:x=&quot;urn:schemas-microsoft-com:offi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string emprah_monde_natal {
            get {
                return ResourceManager.GetString("emprah_monde_natal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description Enfant du Vide..
        /// </summary>
        internal static string EnfantDuVide {
            get {
                return ResourceManager.GetString("EnfantDuVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description Haute Naissance.
        ///
        ///Milieu aisé de l&apos;aristocratie impériale..
        /// </summary>
        internal static string HauteNaissance {
            get {
                return ResourceManager.GetString("HauteNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description Monde Forge..
        /// </summary>
        internal static string MondeForge {
            get {
                return ResourceManager.GetString("MondeForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monde à la population massive, composé de cité-ruches remplies de gangs..
        /// </summary>
        internal static string MondeRuche {
            get {
                return ResourceManager.GetString("MondeRuche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description Monde Saint..
        /// </summary>
        internal static string MondeSaint {
            get {
                return ResourceManager.GetString("MondeSaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un monde dépourvu de civilisation où les plus forts survivent..
        /// </summary>
        internal static string MondeSauvage {
            get {
                return ResourceManager.GetString("MondeSauvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Milieu aisé de l&apos;aristocratie impériale..
        /// </summary>
        internal static string msg_haute_naissance {
            get {
                return ResourceManager.GetString("msg_haute_naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string msg_monde_sauvage {
            get {
                return ResourceManager.GetString("msg_monde_sauvage", resourceCulture);
            }
        }
    }
}
